### ISSUE TITLE
SonarQube Api Importer support multi branch

### ISSUE THREAD

**Issue by nibiwodong** [DefectDojo/django-DefectDojo#5792] opened 2022-01-20 11:43 UTC
**Is your feature request related to a problem? Please describe**
SonarQube api/hotspots/search support branch param, however DefectDojo SonarQube Api Import only use projectKey param to request bugs and hotspots.
[https://github.com/DefectDojo/django-DefectDojo/blob/master/dojo/tools/sonarqube_api/importer.py](url)
![image](https://user-images.githubusercontent.com/17465789/150332234-24b4e3bf-be8d-414f-b5fd-1d377998f087.png)
![image](https://user-images.githubusercontent.com/17465789/150332271-9e7230dd-237e-4244-a788-1a5b1548638d.png)

**Describe the solution you'd like**
Holp to add branch param into function find_issues and find_hotspots, default branch value can be master.

**Comment by valentijnscholten** [comment] 2022-01-20 14:10
duplicate of #5348 ?

**Comment by damiencarol** [comment] 2022-01-21 16:32
> duplicate of #5348 ?

Yes you're right.

**Closed by damiencarol** 2022-01-21 16:32 UTC
Labels: enhancement
