### ISSUE TITLE
'User has no usercontactinfo' error on uploading nessus report

### ISSUE THREAD

**Issue by itsgauravjain22** [DefectDojo/django-DefectDojo#898] opened 2019-02-25 08:46 UTC
### Issue Type 
- [x] Bug
- [ ] Enhancement

### Description
The following error is thrown on uploading nessus scan.
```
RelatedObjectDoesNotExist at /engagement/1/import_scan_results
User has no usercontactinfo.
Request Method:	POST
Request URL:	http://localhost:8000/engagement/1/import_scan_results
Django Version:	1.11.20
Exception Type:	RelatedObjectDoesNotExist
Exception Value:	
User has no usercontactinfo.
Exception Location:	/opt/dojo/local/lib/python2.7/site-packages/django/db/models/fields/related_descriptors.py in __get__, line 407
Python Executable:	/opt/dojo/bin/python
Python Version:	2.7.15
Python Path:	
['/opt/dojo/django-DefectDojo',
 '/opt/dojo/lib/python2.7',
 '/opt/dojo/lib/python2.7/plat-x86_64-linux-gnu',
 '/opt/dojo/lib/python2.7/lib-tk',
 '/opt/dojo/lib/python2.7/lib-old',
 '/opt/dojo/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/opt/dojo/local/lib/python2.7/site-packages',
 '/opt/dojo/lib/python2.7/site-packages',
 '/opt/dojo/django-DefectDojo']
Server time:	Mon, 25 Feb 2019 08:33:27 +0000
```

### Operating System 
Linux Mint 19 Cinnamon

### Install

- [x] setup.bash
- [ ] docker

with mysql database at the core.

### DefectDojo Version
1.5.2

### Steps to Reproduce

- Create the engagement for the product.

- Upload the nessus scan report.

- Observe the error.

### Screenshots (optional)
![1](https://user-images.githubusercontent.com/11793930/53324597-3350d300-3907-11e9-9a44-2e2f653501db.png)

**Comment by p3r1c0** [comment] 2019-03-07 14:57
i have the same error uploading other reports.

**Comment by h00die** [comment] 2019-03-07 21:52
This is caused by an incomplete User object.
When a User is created either through the `manage.py` super user creation, or through a direct object call (`models.User(username='admin', first_name='admin', last_name='admin', email='admin@admin.com').save()`, the corresponding `UserContactInfo` object isn't created.  The code should handle this, but doesn't, and its only in rare circumstances it happens (because you didn't use the UI to create your users, or used superadmin, which is never a good idea).

Solution 1: use a legit user
Solution 2: make the associated data:
```
from dojo import models
u = models.User.objects.get(username=username)
try:
    u.usercontactinfo
except models.UserContactInfo.DoesNotExist:
    uci = models.UserContactInfo(user = u)
    uci.save()
```
While this will stop the error from occuring, your object will be more or less empty.

**Comment by devGregA** [comment] 2019-06-03 13:40
@devEricA I think the fundamental  problem is people are using the root user. @devEricA please verify this issue and then we'll discuss solutions.

**Comment by devEricA** [comment] 2019-06-03 14:50
Seems to be the case @devGregA. I tested both of the nessus sample scan files, both of which ran ok with the admin user.

**Comment by devGregA** [comment] 2019-06-03 15:04
Not able to reproduce in latest version of Dojo. Closing.

**Closed by devGregA** 2019-06-03 15:04 UTC
Labels: Beginner Friendly
