### ISSUE TITLE
GET /finding/<finding_id> 500s when associated Endpoint host is longer than 50 characters

### ISSUE THREAD

**Issue by johnlanda** [DefectDojo/django-DefectDojo#3117] opened 2020-10-28 16:50 UTC
**Bug description**
GET `/finding/<finding_id>` 500s when the associated Endpoint host is longer than 50 characters.

**Steps to reproduce**
1. For a given finding of `<finding_id>`, update one of the endpoints to have a hostname that is greater than 50 characters
2. GET `/finding/<finding_id>`

**Expected behavior**
The `url_shortner` filter should properly handle return values of greater than 50 characters

**Deployment method**
- [ ] Kubernetes
- [X] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: macOS Catalina Version 10.15.5
 - DefectDojo Commit Message: `[2020-10-28 09:12:41 +0100] bfcc9fd9: APIv2 findings performance improvements (#3011) [ (HEAD -> dev, upstream/dev)]`

**Comment by valentijnscholten** [comment] 2020-10-28 17:40
what error are you seeing? For me its works fine with endpoint https://longlonglonglonglonglonglonglonglonglonglonglonglong.com

**Comment by johnlanda** [comment] 2020-10-28 17:52
Here is an example stacktrace: 
```
uwsgi_1         | Internal Server Error: /finding/5
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
uwsgi_1         |     response = get_response(request)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
uwsgi_1         |     response = self.process_exception_by_middleware(e, request)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
uwsgi_1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
uwsgi_1         |   File "./dojo/user/helper.py", line 77, in _wrapped
uwsgi_1         |     return view_func(request, lookup_value, *args, **kwargs)
uwsgi_1         |   File "./dojo/finding/views.py", line 342, in view_finding
uwsgi_1         |     'similar_findings_filter': similar_findings_filter
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
uwsgi_1         |     content = loader.render_to_string(template_name, context, request, using=using)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
uwsgi_1         |     return template.render(context, request)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
uwsgi_1         |     return self.template.render(context)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 171, in render
uwsgi_1         |     return self._render(context)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
uwsgi_1         |     return self.nodelist.render(context)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 937, in render
uwsgi_1         |     bit = node.render_annotated(context)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
uwsgi_1         |     return self.render(context)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
uwsgi_1         |     return compiled_parent._render(context)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
uwsgi_1         |     return self.nodelist.render(context)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 937, in render
uwsgi_1         |     bit = node.render_annotated(context)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
uwsgi_1         |     return self.render(context)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
uwsgi_1         |     result = block.nodelist.render(context)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 937, in render
uwsgi_1         |     bit = node.render_annotated(context)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
uwsgi_1         |     return self.render(context)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/template/loader_tags.py", line 188, in render
uwsgi_1         |     return template.render(context)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 173, in render
uwsgi_1         |     return self._render(context)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
uwsgi_1         |     return self.nodelist.render(context)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 937, in render
uwsgi_1         |     bit = node.render_annotated(context)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
uwsgi_1         |     return self.render(context)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/template/defaulttags.py", line 309, in render
uwsgi_1         |     return nodelist.render(context)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 937, in render
uwsgi_1         |     bit = node.render_annotated(context)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
uwsgi_1         |     return self.render(context)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/template/defaulttags.py", line 513, in render
uwsgi_1         |     return self.nodelist.render(context)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 937, in render
uwsgi_1         |     bit = node.render_annotated(context)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
uwsgi_1         |     return self.render(context)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/template/defaulttags.py", line 309, in render
uwsgi_1         |     return nodelist.render(context)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 937, in render
uwsgi_1         |     bit = node.render_annotated(context)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
uwsgi_1         |     return self.render(context)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/template/defaulttags.py", line 209, in render
uwsgi_1         |     nodelist.append(node.render_annotated(context))
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
uwsgi_1         |     return self.render(context)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 987, in render
uwsgi_1         |     output = self.filter_expression.resolve(context)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/template/base.py", line 698, in resolve
uwsgi_1         |     new_obj = func(obj, *arg_vals)
uwsgi_1         |   File "./dojo/templatetags/display_tags.py", line 95, in url_shortner
uwsgi_1         |     return_value = "..." + return_value[50:]
uwsgi_1         | TypeError: 'Endpoint' object is not subscriptable
```

**Comment by johnlanda** [comment] 2020-10-28 17:57
I agree that it looks like `type(return_value)` should be string already after its initial assignment.

```
@register.filter(name='url_shortner')
def url_shortner(value):
    return_value = str(value)
    url = urlparse(return_value)

    if url.path:
        return_value = url.path
        if len(return_value) == 1:
            return_value = value
    if len(str(return_value)) > 50:
        return_value = "..." + return_value[50:]

    return return_value
```

The stack trace shows that it is still of type `Endpoint` however when trying to grab the truncated return value.

```
uwsgi_1         |   File "./dojo/templatetags/display_tags.py", line 95, in url_shortner
uwsgi_1         |     return_value = "..." + return_value[50:]
uwsgi_1         | TypeError: 'Endpoint' object is not subscriptable
```

I wonder if someone has run into this before because when getting the length of the return value it is cast to a string.

```
# why not just len(return_value) if it were already a string?
if len(str(return_value)) > 50:
```

Note that you will not see this error if `url.path` is truthy

**Comment by valentijnscholten** [comment] 2020-10-28 18:02
what's the endpoint value you're using? I can't reproduce it here.

**Comment by valentijnscholten** [comment] 2020-10-28 18:04
I think the lines before the truncate part might be messing it up, asisgning endpoint instance to return_value again.
![image](https://user-images.githubusercontent.com/4426050/97477812-622b1200-1950-11eb-97fb-a75a6ade179b.png)

**Comment by valentijnscholten** [comment] 2020-10-28 18:04
So i'd prefer to change that assignment

**Comment by johnlanda** [comment] 2020-10-28 18:06
I just tried with 

```
Protocol: http
Host: longlonglonglonglonglonglonglonglonglonglonglonglong.com
Fqdn:
Port:
Path: /
Query:
Fragment:
Tags:
```

and was able to reproduce.

Branch: `dev`
Commit: `[2020-10-28 09:12:41 +0100] bfcc9fd9: APIv2 findings performance improvements (#3011) [ (HEAD -> dev, upstream/dev)]`

Setup: docker
```
cp dojo/settings/settings.dist.py dojo/settings/settings.py
docker/setEnv.sh dev
docker-compose build
docker-compose up
```

I am happy to refactor that block. I agree that would be cleaner and less error-prone in the future.

**Comment by johnlanda** [comment] 2020-10-28 18:08
And nice catch. That is definitely the problem.

**Comment by valentijnscholten** [comment] 2020-10-28 18:08
I reproduced it with '/' as path.  The whole function is crazy tbh :-) If a value is 51 characters, it will show only the last one :-)
But feel free to refactor it into something more robust and more sense making :-)

**Comment by johnlanda** [comment] 2020-10-28 18:10
Sounds good! Thanks for being so responsive! The simplest fix is going to be changing it to something like this. I will play around with it a bit and update the PR.

```
@register.filter(name='url_shortner')
def url_shortner(value):
    return_value = str(value)
    url = urlparse(return_value)

    if url.path and len(url.path) != 1:
        return_value = url.path
    if len(str(return_value)) > 50:
        return_value = "..." + return_value[50:]

    return return_value
```

**Comment by valentijnscholten** [comment] 2020-10-28 18:13
return_value[:50] would be better?

**Comment by johnlanda** [comment] 2020-10-28 18:19
Good call. I think that would make much more sense.

**Comment by valentijnscholten** [comment] 2020-10-28 18:22
actually it make no sense haha. the idea would be to have the last 50 characters, so that would become
return_value[-50:]

**Comment by valentijnscholten** [comment] 2020-10-28 18:23
maybe the if isn't needed and you just always slice it like that

**Comment by valentijnscholten** [comment] 2020-10-28 18:23
oh wait the dots haha

**Comment by johnlanda** [comment] 2020-10-28 18:24
Haha no worries I knew what you were going for. Updated the PR.

**Comment by valentijnscholten** [comment] 2020-10-28 18:25
but.... it should be return_value[-47:]

**Comment by valentijnscholten** [comment] 2020-10-28 18:42
changed it on your PR, sorry to nitpick

**Comment by valentijnscholten** [comment] 2021-02-28 19:53
fixed in that PR

**Closed by valentijnscholten** 2021-02-28 19:53 UTC
Labels: bug
