### ISSUE TITLE
Roles and permissions of users (superuser) do not work!

### ISSUE THREAD

**Issue by undelete** [DefectDojo/django-DefectDojo#2234] opened 2020-04-21 17:19 UTC
**User permissions and roles don't work**
User permissions do not work or even being superusers apply the changes to assigned products. I tried to apply change in the interface of django (Admin) for the users to certain modules but they do not apply either.
**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [ x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [Ubuntu 18.04]
 - DefectDojo Commit Message: [use `git show -s --format="%h: %s [%ci]"`]
**Screenshots** (optional)

<img width="1225" alt="Captura_de_Pantalla_2020-04-21_a_la_s__13_04_02" src="https://user-images.githubusercontent.com/25057634/79893801-91295f80-83d2-11ea-859f-fd0b8c1c49a5.png">
<img width="1010" alt="Captura_de_Pantalla_2020-04-21_a_la_s__13_05_25" src="https://user-images.githubusercontent.com/25057634/79893857-a0a8a880-83d2-11ea-95e0-b9788d300e28.png">
<img width="664" alt="Captura_de_Pantalla_2020-04-21_a_la_s__13_00_22" src="https://user-images.githubusercontent.com/25057634/79893872-a605f300-83d2-11ea-9a73-b389de0ac050.png">

**Comment by dayal18** [comment] 2020-04-24 01:35
Yeah doesn't work, I tried this as well.

**Comment by mahirrudin** [comment] 2020-04-26 23:42
i think this is expected, as superuser you dont need permission. Because by default superuser have all privilege access.

**Comment by dayal18** [comment] 2020-04-27 02:29
I tried for a user without any special permission and it didn't work either.

**Comment by xens** [comment] 2020-05-12 08:21
I agree that there's something wrong with these SuperUser permissions.
Steps to reproduce:

1. Create a new user
2. Tick the "SuperUser" box
3. Select the "Authorized Products" to which the user should have SuperUser permissions
4. Login with the new user
5. You can access the product but only in read-only mode it's not possible to edit the product or add a new engagement and so on...

**Comment by valentijnscholten** [comment] 2020-05-12 20:34
duplicate of #1048

**Closed** 2020-06-30 21:24 UTC
Labels: bug, duplicate
