### ISSUE TITLE
Login error due to incompatible PyJWT dependency

### ISSUE THREAD

**Issue by breckwoldt** [DefectDojo/django-DefectDojo#3556] opened 2020-12-28 00:56 UTC
I can´t login in defectdojo after first installation.

I use the Version 1.10.4 and Docker deployment. After docker-compose up i reach the webinterface on localhost:8080.

When i try to login i get an Server Error 500. On the commandline i find these information:

uwsgi_1         | ERROR:django.request:Internal Server Error: /login
uwsgi_1         | Traceback (most recent call last):
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
uwsgi_1         |     response = get_response(request)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
uwsgi_1         |     response = self.process_exception_by_middleware(e, request)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
uwsgi_1         |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
uwsgi_1         |     return self.dispatch(request, *args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
uwsgi_1         |     return bound_method(*args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
uwsgi_1         |     return view(request, *args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
uwsgi_1         |     return bound_method(*args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
uwsgi_1         |     response = view_func(request, *args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
uwsgi_1         |     return bound_method(*args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
uwsgi_1         |     response = view_func(request, *args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/views.py", line 61, in dispatch
uwsgi_1         |     return super().dispatch(request, *args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
uwsgi_1         |     return handler(request, *args, **kwargs)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/views/generic/edit.py", line 141, in post
uwsgi_1         |     if form.is_valid():
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 185, in is_valid
uwsgi_1         |     return self.is_bound and not self.errors
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 180, in errors
uwsgi_1         |     self.full_clean()
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 382, in full_clean
uwsgi_1         |     self._clean_form()
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/forms/forms.py", line 409, in _clean_form
uwsgi_1         |     cleaned_data = self.clean()
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/forms.py", line 205, in clean
uwsgi_1         |     self.user_cache = authenticate(self.request, username=username, password=password)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 66, in authenticate
uwsgi_1         |     for backend, backend_path in _get_backends(return_tuples=True):
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 27, in _get_backends
uwsgi_1         |     backend = load_backend(backend_path)
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 21, in load_backend
uwsgi_1         |     return import_string(path)()
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/django/utils/module_loading.py", line 17, in import_string
uwsgi_1         |     module = import_module(module_path)
uwsgi_1         |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
uwsgi_1         |     return _bootstrap._gcd_import(name[level:], package, level)
uwsgi_1         |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
uwsgi_1         |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
uwsgi_1         |   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
uwsgi_1         |   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
uwsgi_1         |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
uwsgi_1         |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
uwsgi_1         |   File "/usr/local/lib/python3.6/site-packages/social_core/backends/azuread_tenant.py", line 6, in <module>
uwsgi_1         |     from jwt import DecodeError, ExpiredSignature, decode as jwt_decode
uwsgi_1         | ImportError: cannot import name 'ExpiredSignature'

Who can help me?

best regards from Germany

**Comment by valentijnscholten** [comment] 2020-12-28 08:27
See https://github.com/DefectDojo/django-DefectDojo/pull/3536

**Comment by madchap** [comment] 2020-12-28 08:30
We've got a new release coming up tomorrow too (1.11.0).

**Comment by mfocuz** [comment] 2020-12-29 14:31
Should this problem be fixed already? I still have the same error after pulling changes.

**Comment by breckwoldt** [comment] 2020-12-29 15:41
Yes the change of the requirements.txt have fix my problem.

**Comment by damiencarol** [comment] 2020-12-30 11:27
Clearly a duplicate of #3536. Could we close it @valentijnscholten @madchap ?

**Comment by valentijnscholten** [comment] 2020-12-30 11:33
It's not a duplicate because that is a PR.

**Comment by valentijnscholten** [comment] 2020-12-30 11:33
Fixed in 1.11.0

**Closed by valentijnscholten** 2020-12-30 11:33 UTC
Labels: bug
