### ISSUE TITLE
User creation and management API

### ISSUE THREAD

**Issue by cpandya2909** [DefectDojo/django-DefectDojo#2466] opened 2020-06-03 06:06 UTC
Currently there no API to create a new user or to edit it.

**Comment by JoseRoman** [comment] 2020-06-03 23:14
Duplicate of #1873

**Comment by valentijnscholten** [comment] 2020-06-04 20:30
closing as duplicate, but we understand it might be helpful. not sure if django provides something out of the box.

**Closed by valentijnscholten** 2020-06-04 20:30 UTC
Labels: enhancement

**Comment by cpandya2909** [comment] 2020-06-16 07:36
So this means there will be no API support for user creation and management?

**Comment by cpandya2909** [comment] 2020-06-24 11:30
@valentijnscholten , can you suggest me some temp solution to create users as my production setup is pending due to not able to onboard users.
