### ISSUE TITLE
Error during upload report via UI or API in 2.35.0 (2.35.1 as well)

### ISSUE THREAD

**Issue by zerta664** [DefectDojo/django-DefectDojo#10362] opened 2024-06-07 17:10 UTC
**Bug description**
Impossible to upload report file neither via UI or  via API in new versions(2.35.0 and 2.35.1). Import is failed.

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [X ] Kubernetes
- [ ] GoDojo

**Environment information**
 - Operating System: AWS EKS 1.28
 - DefectDojo version (see footer) or commit message: [2.35.0(1)]

**Logs** 
`{"message": "REIMPORT_SCAN: Collecting Findings", "time": "2024-06-07T07:45:13.941590+00:00"}
{"message": "'tuple' object has no attribute 'get'", "time": "2024-06-07T07:45:13.941706+00:00", "exc_info": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/rest_framework/views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/rest_framework/mixins.py\", line 19, in create\n    self.perform_create(serializer)\n  File \"/app/dojo/api_v2/views.py\", line 2801, in perform_create\n    serializer.save(push_to_jira=push_to_jira)\n  File \"/app/dojo/api_v2/serializers.py\", line 2590, in save\n    self.process_scan(auto_create_manager, data, context)\n  File \"/app/dojo/api_v2/serializers.py\", line 2542, in process_scan\n    ).process_scan(\n      ^^^^^^^^^^^^^\n  File \"/app/dojo/importers/default_reimporter.py\", line 100, in process_scan\n    ) = self.determine_process_method(self.parsed_findings, **kwargs)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/app/dojo/importers/base_importer.py\", line 258, in determine_process_method\n    return self.async_process_findings(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/app/dojo/importers/default_reimporter.py\", line 342, in async_process_findings\n    ) = results.get()\n        ^^^^^^^^^^^\nAttributeError: 'tuple' object has no attribute 'get'"}
[07/Jun/2024 07:45:14] ERROR [django.request:241] Internal Server Error: /api/v2/reimport-scan/
[pid: 19|app: -|req: -/-] 10.44.10.21 (-) {48 vars in 849 bytes} [Fri Jun  7 07:44:55 2024] POST /api/v2/reimport-scan/ => generated 59 bytes in 18886 msecs (HTTP/1.1 500) 8 headers in 253 bytes (1 switches on core 1)`

We use defectdojo on Kubernetes and faced this issue in the latest versions 2.35.0 and 2.35.1 (2.32.2 works)

When we try to upload report via UI we see this error 
`An exception error occurred during the report import: 'list' object has no attribute 'get'`
![image (3)](https://github.com/DefectDojo/django-DefectDojo/assets/37473396/64c1e185-72f1-444e-aba1-e4dfb4d498ce)

We investigated logs and see **following warn in nginx** 
`2024/06/07 07:21:43 [warn] 12#12: *31400 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000005, client: 10.44.7.169, server: , request: "POST /engagement/6314/import_scan_results HTTP/1.1`

**And errors in uwsgi  logs**
`{"message": "dojo_async_task <@task: dojo.finding.helper.post_process_finding_save of dojo at 0x7fa6cac8a910>: no current user, running task in the background", "time": "2024-06-07T07:21:57.653366+00:00"}
{"message": "IMPORT_SCAN: Collecting Findings", "time": "2024-06-07T07:22:00.042754+00:00"}
{"message": "'list' object has no attribute 'get'", "time": "2024-06-07T07:22:00.042840+00:00", "exc_info": "Traceback (most recent call last):\n  File \"/app/dojo/engagement/views.py\", line 931, in import_findings\n    context[\"test\"], _, finding_count, closed_finding_count, _, _, _ = importer_client.process_scan(\n                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/app/dojo/importers/default_importer.py\", line 108, in process_scan\n    new_findings = self.determine_process_method(self.parsed_findings, **kwargs)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/app/dojo/importers/base_importer.py\", line 258, in determine_process_method\n    return self.async_process_findings(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/app/dojo/importers/default_importer.py\", line 383, in async_process_findings\n    serial_new_findings = results.get()\n                          ^^^^^^^^^^^\nAttributeError: 'list' object has no attribute 'get'"}
[pid: 19|app: -|req: -/-] 10.44.7.169 (admin) {74 vars in 3772 bytes} [Fri Jun  7 07:21:44 2024] POST /engagement/6314/import_scan_results => generated 0 bytes in 16727 msecs (HTTP/1.1 302) 9 headers in 534 bytes (1 switches on core 0)
{"message": "Authenticated user: admin", "time": "2024-06-07T07:22:01.146584+00:00"} `

**and when we tried to use API got similar error**

`{"message": "REIMPORT_SCAN: Collecting Findings", "time": "2024-06-07T07:45:13.941590+00:00"}
{"message": "'tuple' object has no attribute 'get'", "time": "2024-06-07T07:45:13.941706+00:00", "exc_info": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/rest_framework/views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/rest_framework/mixins.py\", line 19, in create\n    self.perform_create(serializer)\n  File \"/app/dojo/api_v2/views.py\", line 2801, in perform_create\n    serializer.save(push_to_jira=push_to_jira)\n  File \"/app/dojo/api_v2/serializers.py\", line 2590, in save\n    self.process_scan(auto_create_manager, data, context)\n  File \"/app/dojo/api_v2/serializers.py\", line 2542, in process_scan\n    ).process_scan(\n      ^^^^^^^^^^^^^\n  File \"/app/dojo/importers/default_reimporter.py\", line 100, in process_scan\n    ) = self.determine_process_method(self.parsed_findings, **kwargs)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/app/dojo/importers/base_importer.py\", line 258, in determine_process_method\n    return self.async_process_findings(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/app/dojo/importers/default_reimporter.py\", line 342, in async_process_findings\n    ) = results.get()\n        ^^^^^^^^^^^\nAttributeError: 'tuple' object has no attribute 'get'"}
[07/Jun/2024 07:45:14] ERROR [django.request:241] Internal Server Error: /api/v2/reimport-scan/
[pid: 19|app: -|req: -/-] 10.44.10.21 (-) {48 vars in 849 bytes} [Fri Jun  7 07:44:55 2024] POST /api/v2/reimport-scan/ => generated 59 bytes in 18886 msecs (HTTP/1.1 500) 8 headers in 253 bytes (1 switches on core 1)`

**Comment by mtesauro** [comment] 2024-06-07 21:15
FWIW, I don't see this issue in the public demo:
![image](https://github.com/DefectDojo/django-DefectDojo/assets/3422419/b3940637-1c8a-45b3-891e-b855f38eb594)

The [public demo](https://github.com/DefectDojo/django-DefectDojo?tab=readme-ov-file#demo) is running 2.35.1 and I used an Accunetix file from https://github.com/DefectDojo/sample-scan-files without issue.
![image](https://github.com/DefectDojo/django-DefectDojo/assets/3422419/e22e9102-142f-47b6-9581-8a97e67ec85c)

I'd think there's something going on that is specific to your install or your k8s setup but I'm guessing.

**Comment by zerta664** [comment] 2024-06-10 07:41
@mtesauro  Hi! Sorry, but I don't agree, on the same EKS cluster in the same namespace on the same worker nodegroup version 2.32.0 doesn't have this issue, also you can check Slack channel I see that another person also complain about problems with upload in the latest version

**Comment by kiblik** [comment] 2024-06-10 09:49
The issue is connected to `DD_ASYNC_FINDING_IMPORT`. For a quick fix, disable this functionality, until it is fixed.

More info: https://owasp.slack.com/archives/C2P5BA8MN/p1717758387370009?thread_ts=1717523341.147629&cid=C2P5BA8MN

**Comment by mtesauro** [comment] 2024-06-10 15:36
@kiblik 

> The issue is connected to DD_ASYNC_FINDING_IMPORT. For a quick fix, disable this functionality, until it is fixed.

Makes sense, the public demo doesn't run with that ASYNC_FINDING_IMPORT since that's an experimental feature and should really only be turned on if nothing else sorts out your import issues. It's good for a very narrow set of use-cases but definitely not the most rugged/tested part of DefectDojo.

Thanks for figuring out the issue and sharing. :+1:

**Comment by grendel513** [comment] 2024-06-10 15:51
> The issue is connected to `DD_ASYNC_FINDING_IMPORT`. For a quick fix, disable this functionality, until it is fixed.
> 
> More info: https://owasp.slack.com/archives/C2P5BA8MN/p1717758387370009?thread_ts=1717523341.147629&cid=C2P5BA8MN

@zerta664 @kiblik please note that the documentation is very clear on the status of ASYNC_FINDING_IMPORT: https://documentation.defectdojo.com/getting_started/running-in-production/#asynchronous-import

> Asynchronous Import is currently an experimental feature. Please exercise caution with this method as results may be inconsistent.

This is on our radar, we'll reference this issue in the PR when available.  No specific timeline available yet.

**Comment by mtesauro** [comment] 2024-06-11 02:00
Closing since #10373 was merged

**Closed by mtesauro** 2024-06-11 02:00 UTC
Labels: bug
