### ISSUE TITLE
Latest docker image fails at launch

### ISSUE THREAD

**Issue by raajheshkannaa** [DefectDojo/django-DefectDojo#434] opened 2017-12-22 10:11 UTC
### Issue Type 
- Bug

### Description
- The latest docker image from appsecpipeline/django-defectdojo fails when launching complaining 'No passwd entry for user 'dojo''

### Environment:
- Docker in Windows 7

**Comment by Mason-Fan** [comment] 2018-01-25 11:04
i found the issue also occurs in Linux docker

**Comment by aaronweaver** [comment] 2018-01-25 15:00
@Mason-Fan @raajheshkannaa This issue should be fixed, if you wouldn't mind confirming.

Thanks!

**Comment by devGregA** [comment] 2018-01-25 16:35
Please feel free to reopen if you continue to have issues.

**Closed by devGregA** 2018-01-25 16:35 UTC

**Comment by Mason-Fan** [comment] 2018-01-26 06:45
@devGregA   @aaronweaver  thanks for your help. the issue is fixed. 
but when i run the command 
docker run -it -p 8000:8000 appsecpipeline/django-defectdojo bash -c "export LOAD_SAMPLE_DATA=True && bash /django-DefectDojo/docker/docker-startup.bash"
according to the doc "login with the credentials shown in the terminal.".  but there is no credentials shows.  i tried sometime and found "admin:admin" can login. maybe you can fix the issue or update the documentation.
