### ISSUE TITLE
Upload image to Finding

### ISSUE THREAD

**Issue by wonhee0410** [DefectDojo/django-DefectDojo#9120] opened 2023-12-06 06:47 UTC
**Be informative**
Please enter as much information as possible, otherwise we can't provide support. If possible upgrade to the latest release or dev branch and try again.

**Problem description**
When editing finding, I cannot find a way to upload image directly to DefectDojo (like drag-and-drop image).
The **Insert Image** button just add a link to image on other source.
Please help me how I can upload directly or another way to do that.
Thank you !

**Steps to reproduce**
1. Go to 'Product -> Findings'
2. Click on 'Insert Image'
3. See the link insert 

**Expected behavior**
My expectation is I can upload image directly.

**Deployment method** *(select with an `X`)*
- [X] Docker Compose 
![image](https://github.com/DefectDojo/django-DefectDojo/assets/60768442/17cd1ddf-f089-421a-9002-2ad592a2894e)

**Environment information**
 - Operating System: Redhat 8
 - DefectDojo version: v. 2.27.4

**Comment by mtesauro** [comment] 2024-01-18 03:11
@wonhee0410 Duplicate of #8597 - closing this one

**Closed by mtesauro** 2024-01-18 03:11 UTC
Labels: duplicate
