### ISSUE TITLE
Can't update findings via API with is_mitigated,  false_p, jira_creation

### ISSUE THREAD

**Issue by D4rk4** [DefectDojo/django-DefectDojo#8739] opened 2023-09-27 16:04 UTC
Problem description
I am trying to update findings via the API using a PATCH request. I am sending the request with the necessary data, but the findings are not getting updated as expected. The API returns the unpatched values.

Steps to reproduce

1. Use a PATCH request to update a finding by setting is_mitigated or false_p to true.
2. The API endpoint used is "$API_URL/findings/$finding_id/".
3. The request is sent with the Authorization token and the data payload.
4. The API returns the finding details, but the values are not updated.

Example of the request:

```
curl -s -f -X PATCH -H "Authorization: Token $API_TOKEN" \
     -d '{"is_mitigated": true}' \
     "$API_URL/findings/$finding_id/"
```

**Comment by kiblik** [comment] 2023-09-27 21:54
Which DD version are you using? I tested the same scenario via swagger and it was working.

**Comment by D4rk4** [comment] 2023-09-28 05:02
@kiblik v. 2.24.3 (release mode)

**Comment by kiblik** [comment] 2023-09-28 08:12
I do not see any changes between 2.24.3 and 2.26.4 which might be the reason why it is not working in your 2.24.3 and working in my 2.26.4. But still, try to update, it might start to work.

Or can you try to use `/api/v2/findings/{id}/close/`?

**Comment by D4rk4** [comment] 2023-09-28 12:34
After updating DefectDojo to version 2.26.4, we are still experiencing persistent issues with updating findings attributes.

Additionally, the API endpoint `/api/v2/findings/{id}/close/` is not functioning as expected, preventing the closing of findings through this method. However, closing findings via the User Interface (UI) works seamlessly.

Your assistance in resolving these issues would be greatly appreciated.

**Comment by kiblik** [comment] 2023-11-23 20:06
@D4rk4, sorry for delay.
I found the reason.
If you use `-d '{"is_mitigated": true}'`, you need to explicitly define `-H 'Content-Type: application/json'`. Otherwise `curl` sends `Content-Type: application/x-www-form-urlencoded` and data are not processed correctly.
Or you can use `-d "is_mitigated=true"` (it is the compatible format for `application/x-www-form-urlencoded`).
To be honest, I'm not happy about it. I suppose the endpoint should return `400 Bad Request`, not `200 OK`. I will try to look at it but no guarantees.

**Comment by kiblik** [comment] 2023-11-23 20:42
I tried to add some debug line to `close` action. This is the result.

```shell
$ curl -v -H "Authorization: Token xxx" -d '{"is_mitigated": true}' "http://localhost:8080/api/v2/findings/1/close/" | jq
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /api/v2/findings/1/close/ HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/8.1.2
> Accept: */*
> Authorization: Token xxx
> Content-Length: 22
> Content-Type: application/x-www-form-urlencoded
>
} [22 bytes data]
< HTTP/1.1 200 OK
< Server: nginx
< Date: Thu, 23 Nov 2023 20:31:18 GMT
< Content-Type: application/json
< Content-Length: 119
< Connection: keep-alive
< Allow: POST, OPTIONS
< X-Frame-Options: DENY
< X-Content-Type-Options: nosniff
< Referrer-Policy: same-origin
< Cross-Origin-Opener-Policy: same-origin
< Vary: Cookie
<
{ [119 bytes data]
* Connection #0 to host localhost left intact
{
  "is_mitigated": false,
  "mitigated": "2023-11-23T20:31:18.525875Z",
  "false_p": false,
  "out_of_scope": false,
  "duplicate": false
}
```

Log:
```python
finding_close: FindingCloseSerializer(data=<QueryDict: {'{"is_mitigated": true}': ['']}>)
```

This means that considering `Content-Type: application/x-www-form-urlencoded`, DD recognised `{"is_mitigated": true}` as a key with an empty value. Which is technically correct and we can not blame it.

Some "lessons learned":
- Use swagger. It offers to run tests with both content types and you can see, how the final `curl` should look like.
- Use `-v` instead of `-s` with `curl` during debugging.
- Be careful, which other values are `curl` adding to your requests. It might change expected behaviour.

**Comment by kiblik** [comment] 2023-11-23 20:43
If this helps, please, close the issue.

**Comment by manuel-sommer** [comment] 2024-01-19 19:24
I guess as there was no response till now, we can close the issue @mtesauro ?

**Closed** 2024-01-19 22:04 UTC
