### ISSUE TITLE
jira_link.helper bombs on add_comment_task

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#3488] opened 2020-12-17 09:56 UTC
```
ERROR:django.request:Internal Server Error: /finding/1096260
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./dojo/user/helper.py", line 78, in _wrapped
    return view_func(request, lookup_value, *args, **kwargs)
  File "./dojo/finding/views.py", line 304, in view_finding
    jira_helper.add_comment_task(finding, new_note)
AttributeError: module 'dojo.jira_link.helper' has no attribute 'add_comment_task'
```

**Comment by valentijnscholten** [comment] 2020-12-17 12:46
duplicate of #3453 and fixed in dev

**Closed by valentijnscholten** 2020-12-17 12:46 UTC
Labels: bug
