### ISSUE TITLE
DB-migration-checker container blocks migration job from running in Helm upgrade (2.36.6 to 2.37.0, Chart version 1.6.143 to 1.6.144)

### ISSUE THREAD

**Issue by catshapednoodles** [DefectDojo/django-DefectDojo#10727] opened 2024-08-09 10:45 UTC
**Be informative**
We have DefectDojo deployed on a Kubernetes platform. We mostly use the Helm chart and values provided in the standard Helm chart and Values files in this repository. 
Our current deployment is on Chart version 1.6.143 and we're trying to upgrade to 1.6.144. This kept failing and it's probably because of a wrong order of operations in the Helm deployment.

When upgrading to 2.37.0 (Chart version 1.6.144) the created pods now run an init container called 'db-migration-checker'. This container checks if the migration has succeeded or not, and eventually fails if it doesn't detect a migration.
The pod waits until the init container succeeds before starting the other containers. If it doesn't succeed, the pod is terminated and the upgrade fails.

The migration happens in a job called 'initializer'. This job only runs after a succesful installation or upgrade because of these Helm hooks:
```initializer:
  jobAnnotations: {
    helm.sh/hook: "post-install,post-upgrade"
  }
```
On https://github.com/DefectDojo/django-DefectDojo/blob/master/helm/defectdojo/values.yaml#L302

We use a PostgreSQL database if that matters.

**Bug description**
The 'db-migration-checker' init container checks for a migration that only happens until after the upgrade is completed. 
Because the migration never happens, the init container itself fails, which causes the upgrade to fail and thus the migration job never runs. 

The 'db-migration-checker' needs the migration job to succeed, but the migration job doesn't run until the 'db-migration-checker' container (and the rest of the upgrade) succeeds, which never happens. This is a circular dependency that cannot work in the current order of operations.
Upgrading to 2.37.0 when (mostly) using the standard Helm charts and values is not possible at the moment.

#10454 probably introduced this block on the upgrade, causing this circular dependency.

**Steps to reproduce**
1. Have an existing DefectDojo deployment on 2.36.6 (or other pre-2.37.0) deployed via standard Helm chart (1.6.143 or earlier)
2. Use Helm to upgrade to 2.37.0 (Chart version 1.6.144), make sure to keep dbMigrationChecker enabled
3. The init containers 'db-migration-checker' fail
4. The upgrade fails
5. The migration job never starts

**Expected behavior**
The db-migration-checker doesn't block the upgrade, or the migrations job needs to run while the upgrade is underway.

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [X] Kubernetes
- [ ] GoDojo

**Environment information**
 - DefectDojo version 2.37.0 (from 2.36.6)

**Additional context** (optional)
Our workaround was to disable the dbMigrationChecker:
```
dbMigrationChecker:
  enabled: false
``` 
This caused the upgrade to succeed. We do think checking the migration status before further deploying the application is a good idea, so we would like this circular dependency to get resolved.

**Comment by kiblik** [comment] 2024-08-09 13:15
Thank you @catshapednoodles for this issue, especially for describing the real reason.
Also thanks for describing workaround:
```yaml
dbMigrationChecker:
  enabled: false
```
I haven't bumped into it during development and testing.
I will try to fix it ASAP.

**Comment by fcecagno** [comment] 2024-08-10 00:47
Just thinking aloud, trying to contribute to fixing this issue. I believe the following might fix the issue:
- add an initContainer to initializer job in order to wait for the database to be available (simple port check)
- remove the job annotations from initializer job, so it will run along with the rest of the resources
This way the circular dependency is removed, and might fit well with the current deployment.

**Comment by kiblik** [comment] 2024-08-10 11:50
> Just thinking aloud, trying to contribute to fixing this issue. I believe the following might fix the issue:
> 
> * add an initContainer to initializer job in order to wait for the database to be available (simple port check)
> * remove the job annotations from initializer job, so it will run along with the rest of the resources
>   This way the circular dependency is removed, and might fit well with the current deployment.

From my personal thinking, brainstorming with colleagues, and small talk with the AI chatbot, I come to the same outcome. Happy to see that more people are thinking the same way.

Additionally, I'm considering adding an optional section for more `initContainers` to `initializer-job` which might be useful for `restore-job` (when somebody is performing migration between clusters or as part of disaster recovery; to restore the database). It needs to run after a database is up and running and before running migration (yes, this user-defined job would also have to include the "wait for DB is available" part).

**Comment by kiblik** [comment] 2024-08-12 11:05
I'm having an issue reproducing this scenario locally.
It is not getting stacked. The initializer just starts.
Maybe that is why the tests had passed without any issues.

**Comment by catshapednoodles** [comment] 2024-08-12 11:13
Is there a database migration necessary in one of your test scenarios? The db-migration-checker was stuck on 'Database is not migrated to the latest state yet', which kept repeating. Since that only get logged when the migration check fails (see https://github.com/DefectDojo/django-DefectDojo/blob/master/helm/defectdojo/templates/_helpers.tpl#L140), I suspect that this circular dependency is only blocking when there's a database migration that needs to happen in the initializer job.

**Comment by kiblik** [comment] 2024-08-12 11:21
I fully understand the reason your deployment is stacked. It is correct behavior (considering how chart in `1.6.144` is written).
It is just not happening in my setup. To be honest, it looks more like issue with my setup (it ignores hooks).
I'm just trying to switch from minikube to sth else to run proper tests to be able to fix it.

**Comment by kiblik** [comment] 2024-08-12 13:02
I might found the reason, why my setup has not been failing on circular dependency.
@catshapednoodles, are you using `--wait` in your `helm upgrade`? It is fully correct approach. Just not correctly test in the community helm chart.

**Comment by catshapednoodles** [comment] 2024-08-12 13:24
@kiblik We use `--atomic` which automatically sets the `--wait` flag as well, according to the Helm documentation.

**Comment by kiblik** [comment] 2024-08-12 13:31
Full explanation:
- Running without `--wait` (default behavior): `post-install` and `post-upgrade` hooks are executed in case of successful deployment of the HELM chart. In this context, successful deployment is e.g. successful change of `kind: Deployment` definition. Not full rollout of a new version. So as soon as "kubectl apply" pass, the chart is deployed, and `post-` hooks can be started
- Running with `--wait`: The HELM command waits until all Deployments, StatatefulSets, ... are ready. And `post-` hooks are executed afterward. Unfortunately, `1.6.144` does not allow to declare that Deployments are ready because migrations are not done.

[Following PR](https://github.com/DefectDojo/django-DefectDojo/pull/10744) with [the test](https://github.com/DefectDojo/django-DefectDojo/actions/runs/10352315951/job/28652918248?pr=10744) confirms this hypothesis.

So in my opinion, this issue was there also before but `1.6.144` made it more visible. Before, the upgrade wasn't failing with `--wait` because the deployment's probes had not been failing. If you would run `helm install` (or `helm upgrade --install`) with `--wait` (as you can see in #10744), it would fail. After the first successful install, probes usually pass (even if migrations are not fully finished).

Now, I know better how to test it and I will try to prepare a fixed version of the chart soonish.

**Comment by kiblik** [comment] 2024-08-12 17:35
PR #10740 is ready and tested also with `--wait` (in #10744). Not sure it will be accepted and released as `2.37.1` but hopefully maintainers will be able to check it before `2.37.2`.

**Comment by mtesauro** [comment] 2024-08-13 00:40
@kiblik Correct about not making 2.37.1 but they are targeted for 2.37.2 :+1:

**Comment by vovtz** [comment] 2024-08-19 16:22
> Thank you @catshapednoodles for this issue, especially for describing the real reason. Also thanks for describing workaround:
> 
> ```yaml
> dbMigrationChecker:
>   enabled: false
> ```
> 
> I haven't bumped into it during development and testing. I will try to fix it ASAP.

Unfortunately, this doesn’t work for me (BTW, we deploy with _ArgoCD_, it probably forces the `--wait` flag).

The `defectdojo-django-xxx-yyy` pod’s `uwsgi` container fails with:

```log
*** Operational MODE: preforking+threaded ***
[19/Aug/2024 16:16:27] INFO [dojo.models:4562] enabling audit logging
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x7fa7b291a658 pid: 1 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 1, cores: 2)
spawned uWSGI worker 2 (pid: 19, cores: 2)
[19/Aug/2024 16:16:34] ERROR [django.request:241] Internal Server Error: /login
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/psycopg/cursor.py", line 97, in execute
    raise ex.with_traceback(None)
psycopg.errors.UndefinedTable: relation "django_site" does not exist
LINE 1: ..."django_site"."domain", "django_site"."name" FROM "django_si...
                                                             ^
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/decorators.py", line 186, in _wrapped
    return fn(request, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/decorators.py", line 186, in _wrapped
    return fn(request, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/dojo/user/views.py", line 153, in login_view
    return DojoLoginView.as_view(template_name="dojo/login.html", authentication_form=AuthenticationForm)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

…  

    File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/psycopg/cursor.py", line 97, in execute
    raise ex.with_traceback(None)
django.db.utils.ProgrammingError: relation "django_site" does not exist
LINE 1: ..."django_site"."domain", "django_site"."name" FROM "django_si...
                                                             ^
[uwsgi-http key: defectdojo.apps.toolcluster1.cloud-platform.online client_addr: 10.239.4.124 client_port: 63194] hr_read(): Connection reset by peer [plugins/http/http.c line 918]
[pid: 19|app: -|req: -/-] 10.239.4.124 (-) {30 vars in 440 bytes} [Mon Aug 19 16:16:33 2024] GET /login?force_login_form&next=/ => generated 12833 bytes in 1072 msecs (HTTP/1.1 500) 7 headers in 242 bytes (1 switches on core 0)
[19/Aug/2024 16:16:34] ERROR [django.request:241] Internal Server Error: /login 
```

**Comment by vovtz** [comment] 2024-08-20 14:07
Sorry, the result is not any different, I’m afraid:

![image](https://github.com/user-attachments/assets/e9d004eb-76f5-4f0b-9af3-a1608f833e0f)

**Comment by vovtz** [comment] 2024-08-20 14:08
Or did you mean I should still set this?

```yaml
dbMigrationChecker:
  enabled: false
```

**Comment by kiblik** [comment] 2024-08-20 14:11
`celery(worker|bear)` or `uwsgi` will not start until migration (performed by `initializer`) will not successfully finish. So being stacked in the init container is valid and correct behavior (when you need `dbMigrationChecker` enabled).
The question is: What is the status of the latest `initializer` job/pod?

**Comment by vovtz** [comment] 2024-08-20 14:28
That’s the thing: couldn’t find the _Job_ in ArgoCD, even though it is rendered by `helm template …`. Needed to study the details to realise it’s my own fault this time 😬 … had left the below in the `values.yaml` I pass to ArgoCD:

![image](https://github.com/user-attachments/assets/c2b7b37b-0804-427a-96e3-6b58cd7032ca)

**Comment by vovtz** [comment] 2024-08-20 15:32
> So, is it working now properly?

Yes, after removing those lines, it now works 😅

Thanks a lot for the speedy resolution!

**Comment by mtesauro** [comment] 2024-08-20 23:55
Closing this as it seems resolved. Feel free to reopen or comment if that' s not the case.

**Closed by mtesauro** 2024-08-20 23:55 UTC
Labels: bug
