### ISSUE TITLE
Allow group membership management on the 'edit user' page

### ISSUE THREAD

**Issue by valentijnscholten** [DefectDojo/django-DefectDojo#5499] opened 2021-11-25 16:37 UTC
When editing user currently you can assign a global role, but cannot add the user to any groups. This would require opening each group and add the user there. Easier would be if on the edit user page the groups are shown and you can select/deselect membership for each group.

**Comment by StefanFl** [comment] 2021-11-26 05:44
All the membership view/edit/add functionality is on the view pages for products, product types, users and groups. This is consistent with other areas of DefectDojo. Eg. you add a test from the engagement view page. 

So you can add an user to a group from the view user page. I think the problem is, that adding a user behaves differently from other dialogues. When you add all other objects, you get redirected to the page to view the object. But when you add an user you stay on that page and can edit the user. If we change that and redirect to the view user page, you can add the user to a group, product or product type there. That's an easy fix.

**Comment by valentijnscholten** [comment] 2021-11-26 10:09
Ah yes, I see it. Could be a good solution. Also maybe change the word "Members" to "Memberships": 
![image](https://user-images.githubusercontent.com/4426050/143564032-8dc357fa-2c32-4a3b-ac66-bffc92775179.png)

**Comment by StefanFl** [comment] 2021-12-05 08:08
merged for release 2.5.0

**Closed by StefanFl** 2021-12-05 08:08 UTC
Labels: enhancement
