### ISSUE TITLE
parsers not working in version 1.10.0

### ISSUE THREAD

**Issue by tahir59** [DefectDojo/django-DefectDojo#3361] opened 2020-11-26 10:22 UTC
parsers are not working in version 1.10.0, when uploading files getting (500 Internal Server Error).

refer the logs below:

ERROR:django.request:Internal Server Error: /engagement/8/import_scan_results
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/usr/local/lib/python3.6/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/usr/local/lib/python3.6/site-packages/kombu/serialization.py", line 350, in pickle_dumps
    return dumper(obj, protocol=pickle_protocol)
  File "/usr/local/lib/python3.6/tempfile.py", line 485, in func_wrapper
    return func(*args, **kwargs)
TypeError: cannot serialize '_io.BufferedRandom' object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./dojo/engagement/views.py", line 664, in import_scan_results
    item.save(dedupe_option=False, false_history=True)
  File "./dojo/models.py", line 2158, in save
    do_apply_rules(self, *args, **kwargs)
  File "./dojo/decorators.py", line 38, in __wrapper__
    return func(*args, **kwargs)
  File "./dojo/decorators.py", line 23, in __wrapper__
    return func.delay(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/task.py", line 426, in delay
    return self.apply_async(args, kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/task.py", line 570, in apply_async
    **options
  File "/usr/local/lib/python3.6/site-packages/celery/app/base.py", line 741, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/usr/local/lib/python3.6/site-packages/celery/app/amqp.py", line 561, in send_task_message
    **properties
  File "/usr/local/lib/python3.6/site-packages/kombu/messaging.py", line 169, in publish
    compression, headers)
  File "/usr/local/lib/python3.6/site-packages/kombu/messaging.py", line 252, in _prepare
    body) = dumps(body, serializer=serializer)
  File "/usr/local/lib/python3.6/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/usr/local/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/site-packages/kombu/serialization.py", line 54, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/vine/five.py", line 194, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/usr/local/lib/python3.6/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/usr/local/lib/python3.6/site-packages/kombu/serialization.py", line 350, in pickle_dumps
    return dumper(obj, protocol=pickle_protocol)
  File "/usr/local/lib/python3.6/tempfile.py", line 485, in func_wrapper
    return func(*args, **kwargs)
kombu.exceptions.EncodeError: cannot serialize '_io.BufferedRandom' object

**Comment by valentijnscholten** [comment] 2020-11-26 18:08
Can you provide more info on how to reproduce? We have integration tests running OK and it works for me also.

**Comment by tahir59** [comment] 2020-11-27 04:14
I have tested with harbor and github parser on kubernetes & docker-compose, moreover also django pods are frequently restarting.

**Comment by valentijnscholten** [comment] 2020-11-28 11:00
I think there are some issues with kubernetes overall in 1.10.0 to be fixed in 1.10.1 in a few days.

**Comment by tahir59** [comment] 2020-11-30 07:20
I have upgraded to version 1.10.1 but still same issue. In logs I can continuously see http 403 error through I am not importing anything ...

[pid: 1|app: 0|req: 68/204] X.X.X.X () {52 vars in 961 bytes} [Mon Nov 30 07:18:39 2020] POST /api/v2/import-scan/ => generated 27 bytes in 27 msecs (HTTP/1.1 403) 7 headers in 209 bytes (1 switches on core 1)
[pid: 72|app: 0|req: 137/205] 172.20.46.63 () {52 vars in 961 bytes} [Mon Nov 30 07:18:39 2020] POST /api/v2/import-scan/ => generated 27 bytes in 29 msecs (HTTP/1.1 403) 7 headers in 209 bytes (1 switches on core 1)
[pid: 72|app: 0|req: 139/207] X.X.X.X () {52 vars in 961 bytes} [Mon Nov 30 07:18:42 2020] POST /api/v2/import-scan/ => generated 27 bytes in 24 msecs (HTTP/1.1 403) 7 headers in 209 bytes (1 switches on core 0)
[pid: 72|app: 0|req: 139/208] 172.20.46.63 () {52 vars in 961 bytes} [Mon Nov 30 07:18:42 2020] POST /api/v2/import-scan/ => generated 27 bytes in 23 msecs (HTTP/1.1 403) 7 headers in 209 bytes (1 switches on core 1)
[pid: 1|app: 0|req: 70/209] X.X.X.X () {52 vars in 961 bytes} [Mon Nov 30 07:18:45 2020] POST /api/v2/import-scan/ => generated 27 bytes in 24 msecs (HTTP/1.1 403) 7 headers in 209 bytes (1 switches on core 1)
[pid: 72|app: 0|req: 140/210] 172.20.46.63 () {52 vars in 961 bytes} [Mon Nov 30 07:18:45 2020] POST /api/v2/import-scan/ => generated 27 bytes in 23 msecs (HTTP/1.1 403) 7 headers in 209 bytes (1 switches on core 0)
[pid: 72|app: 0|req: 144/214] 172.20.46.63 () {52 vars in 961 bytes} [Mon Nov 30 07:18:48 2020] POST /api/v2/import-scan/ => generated 27 bytes in 22204 msecs (HTTP/1.1 403) 7 headers in 209 bytes (1 switches on core 1)

**Comment by valentijnscholten** [comment] 2020-12-01 11:14
clearly something is making those requests so you'll have to find our where they are coming from. also check the logs if everything has started correctly.

**Comment by tahir59** [comment] 2020-12-21 04:58
the issue got fixed after adding MemoryFileUploadHandler in below file.

dojo/settings/settings.dist.py

FILE_UPLOAD_HANDLERS = (
    "django.core.files.uploadhandler.MemoryFileUploadHandler",
    "django.core.files.uploadhandler.TemporaryFileUploadHandler"
)

**Closed** 2020-12-30 22:51 UTC
Labels: Support
