### ISSUE TITLE
Configure Travis to run all unit tests in the /tests folder

### ISSUE THREAD

**Issue by Maffooch** [DefectDojo/django-DefectDojo#1492] opened 2019-08-13 18:52 UTC
These tests were written to be used by Travis.

**Comment by ptrovatelli** [comment] 2019-10-15 22:46
@propersam congrats on the first PR on your repo :)
https://github.com/propersam/django-DefectDojo/pull/1
i have fixed the "dedupe_unit_test" in that PR 

It seems that you have already fixed a number of tests, well done!
Do you know if those work with travis? If yes I think you should probably push those that work as soon as possible, and finish the others later. the more we wait, the more people may break tests that currently work, which means more time needed to fix them again.
I have setup an ubuntu VM to run the tests which is probably what you did too; I think we could probably create a new Dockerfile for this environment so that everyone can run the tests locally with docker without the need of ubuntu. I'll have a look at this.

**Comment by propersam** [comment] 2019-10-17 17:51
Yea..many of what i fixed work. Infact almost all the work are suppose to work. I am only encountering a challenge with user permission.

in the Dockerbuild file there is a command that restricts users.
i think it's `USER 1001`. This command limits some of the test and causes permission error. This is what i have been trying to find work around for these past few months.

if that command is command from the Dockerbuild file, all my test current having errors works perfectly but I guess the command is needed and should not be removed.

So I have been think of how a different docker build cn be configured with full permission just for unittest sake. If this can be achieve. my PR will be well ready for merge.

**Comment by propersam** [comment] 2019-10-17 18:02
I think for now..i'm going to have to comment out those tests that requires permission...So that the tests that work cn be merged and the travis unittest test is added to the CI pipeline...

**Comment by ptrovatelli** [comment] 2019-10-17 19:23
@propersam I think I know that issue. for permissions to work properly in the container, that USER id that you put in the Dockerfile should be the same as the host user id (uid) you're using when cloning the git repo because that uid in Dockerfile is the user id that you'll have inside the container, and the files belong to the user outside the container that did the git clone. 
typically it's 1000 instead of 1001 (type simple the command "id" to find out)
The problem is that depending on the host configuration it may vary but i think we can simply add this in the doc so that ppl put their own uid.
 By default we should leave the uid that works for travis, it might be 1001
There are already some words about that issue in the DOCKER.MD: 

*Notes about volume permissions*

*The manual copy of settings.py is sometimes required once after cloning the repository, on linux hosts when the host files cannot be modified from within the django container. In that case that copy in entrypoint-uwsgi-dev.sh fails.* 

*Another way to fix this is changing `USER 1001` in Dockerfile.django to match your user uid and then rebuild the images. Get your user id with* 

```
id -u
```

**Comment by propersam** [comment] 2019-10-17 21:22
Im so so happy right now...
your comments above just gave me the perfect solution i have been looking for.
I was able to add a Sed script that grep and replaces `USER 1000` within the Dockerfile.django file to the uid of the travis runner.
And now all my scripts run fine with no permission error.

I'm going to do some clean up now and reopen my PR

**Comment by propersam** [comment] 2019-10-17 21:50
turns out the uid for the travis runner is not `1000` as i tried to use that at first...but instead with the above script i was able to get the correct uid `2000`
```
Step 19/23 : USER root
 ---> Running in 52cdad720bf4
Removing intermediate container 52cdad720bf4
 ---> 9b303bf1248f
Step 20/23 : RUN chmod -R 0777 /app
 ---> Running in 0dceba273d39
Removing intermediate container 0dceba273d39
 ---> c41680f194fc
Step 21/23 : *USER 2000*
```

**Comment by ptrovatelli** [comment] 2019-10-18 13:07
@propersam glad it worked :)
I have a couple of suggestions after checking the branch you're working on a couple of days ago: 
- dockerfile.django: chmod 777: really necessary? 
- requirements: you have added selenium in the requirements file but it's not required for production. I think it may be enough to install it in the dockerfile
- unit tests from dojo/unittests: maybe not necessary to run them again. I think i've seen them run again from the new script. they are currently run from this command in script.sh: 

```
    helm/defectdojo/templates/tests/unit-tests.yaml
      command: ['/entrypoint-unit-tests.sh']
        entrypoint-unit-tests.sh
          python manage.py makemigrations dojo
          python manage.py migrate
          exec python manage.py test dojo.unittests --keepdb
```
- naming: maybe we should keep a separate name for tests under /tests and the ones under dojo/unittests
  - under dojo/unittests: they are really unitests as they test components of the app using a python testing framework
  - under tests: i'd say those are rather integration tests. some of those were btw called by test\travis-integration-test.sh although i don't think this script is currently called by travis

as a rule of thumb, I'd say that when you need to start the application before running the tests it usually means you're doing integration tests, not unit tests.

**Comment by propersam** [comment] 2019-10-24 23:53
> * requirements: you have added selenium in the requirements file but it's not required for production. I think it may be enough to install it in the dockerfile

I did this while trying to debug my error..forgot to remove...it's definitely not required..It's installed when needed in the travis test...

**Comment by propersam** [comment] 2019-10-25 00:02
> * unit tests from dojo/unittests: maybe not necessary to run them again. I think i've seen them run again from the new script. they are currently run from this command in script.sh:
> 
> ```
>     helm/defectdojo/templates/tests/unit-tests.yaml
>       command: ['/entrypoint-unit-tests.sh']
>         entrypoint-unit-tests.sh
>           python manage.py makemigrations dojo
>           python manage.py migrate
>           exec python manage.py test dojo.unittests --keepdb
> ```

Noted. I now use *setEnv dev* instead of *unit_tests* for the docker-compose-override.

**Comment by propersam** [comment] 2019-10-25 00:06
> * naming: maybe we should keep a separate name for tests under /tests and the ones under dojo/unittests
>   
>   * under dojo/unittests: they are really unitests as they test components of the app using a python testing framework
>   * under tests: i'd say those are rather integration tests. some of those were btw called by test\travis-integration-test.sh although i don't think this script is currently called by travis
> 
> as a rule of thumb, I'd say that when you need to start the application before running the tests it usually means you're doing integration tests, not unit tests.

I kind of agree with u on this...and it really makes sense to me...
cause i have actually been having this confusion in my head yl working on this..nd i've asked these questions....I think it really makes sense like this...

**Comment by madchap** [comment] 2020-01-26 09:56
Hi @propersam, @ptrovatelli 

Anything further to be done here? I also see in @propersam's tree a PR from you Pascal, which got merged but the last comment points to maybe something else?

Cheers.

**Comment by propersam** [comment] 2020-01-26 10:09
This issue is Over..it is okay to close now...

**Comment by ptrovatelli** [comment] 2020-01-26 14:20
@propersam aren't there still some tests that were left out and ought to be fixed one day?

**Comment by propersam** [comment] 2020-01-26 14:31
Yea...there are some tests not working prooerly to be fixed....nd tgere are possibly more tests to be written with every new PR being merged. But those should be for another issue(s).

The purpose of this issue was to implement a C.I test runner into travis that runs d tests from the /tests folder. Which has bn merged now...so other subsequent tests cn nw be added later to d /tests folder nd configured in d travis unittest script.

**Comment by ptrovatelli** [comment] 2020-01-26 14:46
ok!

**Closed by ptrovatelli** 2020-01-26 14:46 UTC
Labels: gsoc
