### ISSUE TITLE
Markdown links and images are getting href and src attributes stripped

### ISSUE THREAD

**Issue by erickmetz** [DefectDojo/django-DefectDojo#6792] opened 2022-09-02 16:33 UTC
Greetings. I've been searching through the GitHub Issues (open and closed) to see if anyone is experiencing a problem that I am having with a new containerized deployment:

In findings, I am totally unable to use the markdown for links or images. The respective `href` and` src` attributes are completely removed from the anchor and image tags. 

I was following this through the different |markdown_render and bleach code and it seems like src and href should not be stripped. And yet when I inspect the elements in the DOM I simply have, for example:
```
<a>PortSwigger</a> 

<img alt="Tesdt02">
```
This is using the precise format the the link and image insertion icons place into the textarea while editing a finding.

**Comment by manuel-sommer** [comment] 2022-09-04 18:06
https://github.com/DefectDojo/django-DefectDojo/issues/6761

**Comment by damiencarol** [comment] 2022-09-04 20:28
Duplicate of #6761

**Closed by damiencarol** 2022-09-04 20:28 UTC
