### ISSUE TITLE
Gitlab Container scan import crash from API without scan_date arg

### ISSUE THREAD

**Issue by sebglon** [DefectDojo/django-DefectDojo#9883] opened 2024-04-05 08:41 UTC
**Slack us first!**
The easiest and fastest way to help you is via Slack. There's a free and easy signup to join our #defectdojo channel in the OWASP Slack workspace: [Get Access.](https://owasp-slack.herokuapp.com/)
If you're confident you've found a bug, or are allergic to Slack, you can submit an issue anyway.

**Be informative**
Please enter as much information as possible, otherwise we can't provide support. If possible upgrade to the latest release or dev version and try again.

**Bug description**

I try to import a Gitlab container scan from API but it fail every time

**Steps to reproduce**

1. generate a gitlab report with versions:
```
    "scan": {
        "scanner": {
            "id": "trivy",
            "name": "Trivy",
            "url": "https://github.com/aquasecurity/trivy/",
            "vendor": {
                "name": "GitLab"
            },
            "version": "0.49.1"
        },
        "analyzer": {
            "id": "gcs",
            "name": "GitLab Container Scanning",
            "vendor": {
                "name": "GitLab"
            },
            "version": "6.7.1"
        },
        "type": "container_scanning",
        "start_time": "2024-04-02T08:26:31",
        "end_time": "2024-04-02T08:27:02",
        "status": "success"
    },
    "version": "15.0.6"
```
2. run curl cmd
```
curl -vvvv --fail -X 'POST' "http://localhost:8080/api/v2/import-scan/" -H "Authorization: Token xxxxx" -F 'file=@gl-container-scanning-report.json' -F 'scan_type=GitLab Container Scan' -F "product_name=core" -F 'engagement_name=GitLab' -F 'product_type_name=Software' --location --form 'verified=true' --form 'active=true' 
```
```
Fri Apr  5 08:14:25 2024 - uwsgi_response_writev_headers_and_body_do(): Broken pipe [core/writer.c line 306] during POST /api/v2/import-scan/ (10.233.111.51)

```

If i run the same cmd with the arg `-F "scan_date=$(date +'%Y-%m-%d')"` all is good

**Expected behavior**
work without setting the scan_date like other reports

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [x] Kubernetes
- [ ] GoDojo

**Environment information**
 - DefectDojo version (see footer) or commit message: v2.31.4

**Comment by manuel-sommer** [comment] 2024-04-08 08:36
Hi @sebglon,

in order to reproduce this issue more easily, it would be helpful if you could provide a sample scan.

**Comment by manuel-sommer** [comment] 2024-04-24 06:18
Hi @sebglon and @Maffooch ,

as far as I can see this is closed. The reason ia that this issue is a duplicate from https://github.com/DefectDojo/django-DefectDojo/issues/9838 and was fixed here: https://github.com/DefectDojo/django-DefectDojo/pull/10018 

Can you please close this @mtesauro ?

**Closed** 2024-04-24 21:00 UTC
Labels: bug
