### ISSUE TITLE
Trivy upload not working 

### ISSUE THREAD

**Issue by Vanye-getcerebral** [DefectDojo/django-DefectDojo#6393] opened 2022-06-08 23:50 UTC
**Bug description**
Trivy k8s scan results would not upload to deject dojo 

**Steps to reproduce**
1. Go to findings
2. Click on import scan results
3. Select trivy scan as scan type

**Expected behavior**
Upload Trivy k8s results scan into dojo

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [ X] Kubernetes
- [ ] GoDojo

**Environment information**
 Self hosted (AWS) v. 2.9.0 ( release mode ) 

**Logs** 
Use `docker-compose logs` (or similar, depending on your deployment method) to get the logs and add the relevant sections here showing the error occurring (if applicable).

**Sample scan files**
If applicable, add sample scan files to help reproduce your problem.

**Screenshots**

![Screen Shot 2022-06-08 at 4 44 00 PM](https://user-images.githubusercontent.com/89488932/172735551-a3fa6c75-7494-4570-a026-0eab94d2c3e0.png)

**Additional context** (optional)

**Comment by StefanFl** [comment] 2022-06-09 07:29
Hi @Vanye-getcerebral, please provide the logs and/or a sample report to reproduce the problem

**Comment by Vanye-getcerebral** [comment] 2022-06-09 21:58
json sample report
[trivy_result.txt](https://github.com/DefectDojo/django-DefectDojo/files/8874192/trivy_result.txt)

**Comment by Vanye-getcerebral** [comment] 2022-06-09 23:54
![Screen Shot 2022-06-09 at 2 18 00 PM](https://user-images.githubusercontent.com/89488932/172963751-c8323d53-7000-4596-b485-3aeffd28977d.png)

**Comment by damiencarol** [comment] 2022-06-10 03:08
@StefanFl @Vanye-getcerebral it's a new beta feature of Trivy. the parser doesn't support these data and need work.

**Comment by StefanFl** [comment] 2022-06-10 06:21
True, so it's not a bug. The parser reports correctly that it doesn't support this schema. I will have a look at it in the next days.

**Comment by damiencarol** [comment] 2022-06-10 14:49
@StefanFl more a missing feature but yeah :) . this thing is new so...

**Comment by damiencarol** [comment] 2022-06-18 19:02
Merged, will be part of the next release.

**Closed by damiencarol** 2022-06-18 19:02 UTC
Labels: enhancement
