### ISSUE TITLE
Demo site have 503 error

### ISSUE THREAD

**Issue by zakrush** [DefectDojo/django-DefectDojo#2479] opened 2020-06-04 09:02 UTC
HEllo. 
I wanted to see  the demo stand of DefectDojo. I clicked on the link into doc https://defectdojo.readthedocs.io/en/latest/getting-started.html

On this site I get the 503 error.  
![image](https://user-images.githubusercontent.com/33844164/83737097-3df62e00-a65b-11ea-8ac3-9db3176c7d45.png)

**Comment by valentijnscholten** [comment] 2020-06-04 15:57
known issue, a new one is in the works.

**Comment by valentijnscholten** [comment] 2020-06-04 15:58
duplicate of #2037

**Closed by valentijnscholten** 2020-06-04 15:58 UTC
Labels: bug
