### ISSUE TITLE
Endpoints not appearing in the GUI for finding

### ISSUE THREAD

**Issue by michaels-ts** [DefectDojo/django-DefectDojo#6787] opened 2022-09-01 17:27 UTC
**Bug description**
It appears that if you create a finding via API, you will need to resave the issue in the GUI for the endpoints to appear in the console as related to the issue.

**Steps to reproduce**
1. Create a finding with an endpoint via the api
2. Go to newly created finding in the console. The endpoint doesn't appear as you initially open the finding
3. Edit that same finding in the GUI and save it making no changes. As you scroll down to the save button, you will notice the endpoint given via api is highlighted.
4. Once saved, you will now seed the endpoint with the issue.

**Expected behavior**
The endpoints should appear with the finding without needing to save it again in the GUI.

**Deployment method** *(select with an `X`)*
- [ ] Docker Compose
- [ ] Kubernetes
- [X] GoDojo

**Environment information**
 - Ubuntu 20.04
 - v. 2.13.1 (been upgrading since 2.0.3)

**Logs** 
Not sure if there where I would need to grab logs from but if I can be pointed a direction I can retrieve them as needed.

**Additional context** (optional)

**Comment by coheigea** [comment] 2022-09-26 06:44
I can't reproduce this issue with calling /api/v2/reimport-scan, the endpoints appear correctly. Can you attach a test-case and exact instructions to reproduce?

**Comment by kiblik** [comment] 2022-10-04 23:11
In the actual implementation of the model, you need to add `Endpoint` to `Finding`and `Endpoint_Status` as well.
This is not the best and it will be fixed in https://github.com/DefectDojo/django-DefectDojo/pull/6193

**Comment by kiblik** [comment] 2022-11-03 16:49
This issue should be fixed by #6193 and released in 2.16.0

@michaels-ts, can you confirm it?

**Comment by manuel-sommer** [comment] 2024-02-07 12:05
I guess this is deprecated. Can you close this @mtesauro ?

**Closed** 2024-02-07 19:58 UTC
Labels: bug
