### ISSUE TITLE
Sonarqube Tests finding mitigations after running Reupload-scan 

### ISSUE THREAD

**Issue by Homopatrol** [DefectDojo/django-DefectDojo#3702] opened 2021-01-21 13:14 UTC
I’ve come across a bug that causes DefectDojo to erroneously flag mitigations when reimporting a Sonarqube test scan. 

I imported a [sonar-report.txt](https://github.com/DefectDojo/defectdojo_api/files/5849498/sonar-report.txt) to DefectDojo

<img width="1659" alt="Screenshot 2021-01-21 at 12 01 52" src="https://user-images.githubusercontent.com/58219367/105355127-86159100-5be9-11eb-897d-cf8e7d042efe.png">

As you can see in the report some errors reported twice however these relate to different components in the project – eg. 
```
"<!DOCTYPE>" Declarations Should Appear Before "<html>" Tags
```
This initial upload provides the following results:

<img width="1032" alt="Screenshot 2021-01-21 at 12 03 31" src="https://user-images.githubusercontent.com/58219367/105353309-fbcc2d80-5be6-11eb-952d-350e15271b97.png">

However, upon reimporting the same report by running the script again DefectDojo seems to find and mitigate 5 results despite the fact I have not changed the report. 

<img width="1028" alt="Screenshot 2021-01-21 at 12 05 44" src="https://user-images.githubusercontent.com/58219367/105353320-fe2e8780-5be6-11eb-84d8-512a956b9da3.png">

This error also appears when reuploading Dependency Track and Dependency Check scans so is there an issue with the way DefectDojo is analysing the test results?

**Comment by valentijnscholten** [comment] 2021-01-24 17:18
duplicate of #3675

**Closed** 2021-01-24 17:19 UTC
