### ISSUE TITLE
CVSS Calculator version is showing as 3.0 instead of 3.1

### ISSUE THREAD

**Issue by tech-surajrk** [DefectDojo/django-DefectDojo#7528] opened 2023-02-01 12:03 UTC
**Bug description**
When we add any new finding and select the vectors from CVSS calculator then it shows CVSS 3.0 and not 3.1. Ideally it should show 3.1. Below is one of the example -
CVSS:3.0/AV:N/AC:H/PR:L/UI:N/S:U/C:H/I:L/A:N

**Steps to reproduce**
1. Go to 'Engagement >> Test >> New Finding'
2. Click on 'CVSSv3 Field'
3. See error below
![image](https://user-images.githubusercontent.com/112088960/216037209-960ead71-ae69-4f3a-bdb6-0522c137ee02.png)

**Expected behavior**
It should show - CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:H/I:L/A:N

**Deployment method** 
- Docker Compose

**Environment information**
 - Operating System: [CentOS]
 - DefectDojo version - 2.18.3

**Comment by damiencarol** [comment] 2023-02-01 18:51
@surajanuja not sure to follow you. Today the UI only support version 3.0. It's a choice, we didn't found components that support the latest version (3.1).
So it's not a bug, you're requesting something new.

**Comment by surajanuja** [comment] 2023-02-01 19:01
> @surajanuja not sure to follow you. Today the UI only support version 3.0. It's a choice, we didn't found components that support the latest version (3.1). So it's not a bug, you're requesting something new.

Thanks for the clarity. I thought 3.1 is already present.

**Comment by manuel-sommer** [comment] 2024-02-01 12:12
Can we close this @mtesauro ?

**Closed** 2024-02-02 02:30 UTC
Labels: bug
