### ISSUE TITLE
Metrics totals not displayed in product view

### ISSUE THREAD

**Issue by cristiano-corrado** [DefectDojo/django-DefectDojo#2040] opened 2020-03-11 19:17 UTC
**Bug description**
Metrics totals not displayed in product view

**Steps to reproduce**
1. upload any scans (I used spotbug xml
2. go in the view of the product where the scan was imported 
3. se the metrics not reflecting the count of issues
**Expected behavior**
the metrics should display the count of issue under each severity

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [x] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: [e.g. Ubuntu 18.04]
 - DefectDojo Commit Message: c46688ce: Merge pull request #1983 from DefectDojo/1.5.4.1 [2020-03-05 15:23:59 -0600]

**Sample scan files** (optional)
N/A

**Screenshots** (optional)
<img width="1031" alt="Screenshot 2020-03-11 at 19 11 52" src="https://user-images.githubusercontent.com/3243602/76454611-df5b4400-63cc-11ea-997a-34909b321cea.png">

<img width="938" alt="Screenshot 2020-03-11 at 19 12 02" src="https://user-images.githubusercontent.com/3243602/76454620-e2563480-63cc-11ea-8be2-26d0be2c2f1c.png">

<img width="1436" alt="Screenshot 2020-03-11 at 19 12 18" src="https://user-images.githubusercontent.com/3243602/76454637-e8e4ac00-63cc-11ea-95bc-37a2d20430b0.png">

**Comment by TheUnriashol** [comment] 2020-03-19 13:44
Just an FYI, this doesnt seem to have been fixed in dev. At least not for me.

But this is not a bug its a feature 😄. 

You have to make sure when uploading findings that you select the Active checkbox. Else they will be imported as inactive findings. This meaning that they will show up in the metrics tab but wont show up in the metrics container on the overview tab.

**Comment by scottgoettepnc** [comment] 2020-06-09 17:49
We're seeing that in build #1.5.4.1 that if you have finding set at "active" and "verified" that it's not pulled into the metrics
@devGregA

**Comment by valentijnscholten** [comment] 2020-06-09 21:37
fixed in 1.6.2

**Closed by valentijnscholten** 2020-06-09 21:37 UTC
Labels: bug, fixed in dev
