### ISSUE TITLE
Not able to upload AWS Prowler Scan Report. Give this error:-  An exception error occurred during the report import:'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by kartikeyj96** [DefectDojo/django-DefectDojo#7968] opened 2023-04-13 12:30 UTC
Hello,

After creating a test type for "AWS Prowler Scan" and the product too. I was uploading the sample report given in official repo of DefectDojo. But it throws this error:

```An exception error occurred during the report import:'NoneType' object has no attribute 'group'```

I tried to change the options but nothing works.

Tried the API way too, but that throws 500 error.

Screenshot:
![image](https://user-images.githubusercontent.com/56039568/231758639-61cf01f0-8c71-4c2e-a15d-703f79de7855.png)

Thanks.

**Comment by kiblik** [comment] 2023-04-13 13:42
Looks like issue in processing regex in one other these two lines
- https://github.com/DefectDojo/django-DefectDojo/blob/dfc36c91e36170108538e79c636517e294fb8612/dojo/tools/aws_prowler/parser.py#L65
- https://github.com/DefectDojo/django-DefectDojo/blob/dfc36c91e36170108538e79c636517e294fb8612/dojo/tools/aws_prowler/parser.py#L144

If you would be able to provide an anonymized version of your report, it could help in troubleshooting.

**Comment by awakenine** [comment] 2023-05-12 07:51
Duplicate of https://github.com/DefectDojo/django-DefectDojo/issues/7348

**Comment by manuel-sommer** [comment] 2024-01-21 01:11
The duplicate issue was closed due to a fix. this can be closed as far as I can see this @mtesauro

**Closed** 2024-01-21 01:58 UTC
Labels: bug
