### ISSUE TITLE
Cannot create Jira cloud configuration

### ISSUE THREAD

**Issue by praveendvd** [DefectDojo/django-DefectDojo#3179] opened 2020-11-05 12:33 UTC
Gets incorrect user name ,url or password error

**Steps to reproduce**
1) create a token from jira cloud account
2) provide url as https://<jiracloud>.net/jira
3) provide username as email address used in jira cloud
4) provide password as API token

**Expected behavior**

SHould create configuration successfully

**Deployment method** *(select with an `X`)*

- [x ] Docker

**Environment information**
 - Operating System:  CentOS Linux release 8.2.2004 (Core) 
 - DefectDojo Commit Message:[2020-10-29 16:05:41 +0100] 00cbddad: Update .travis.yml [ (HEAD -> master, origin/master, origin/HEAD)]

log:
[file.log](https://github.com/DefectDojo/django-DefectDojo/files/5494345/file.log)

Screenshots:

![image](https://user-images.githubusercontent.com/45095911/98167576-33c5ad80-1ee1-11eb-9a25-2121042531bb.png)

![image](https://user-images.githubusercontent.com/45095911/98241344-b8a4db80-1f62-11eb-9043-70c5bd34820e.png)

**Comment by valentijnscholten** [comment] 2020-11-05 17:04
duplicate of #3176

**Closed by valentijnscholten** 2020-11-05 17:04 UTC
Labels: bug
