### ISSUE TITLE
Error importing Checkmarx results. Ignored active and verified state

### ISSUE THREAD

**Issue by ssiriz** [DefectDojo/django-DefectDojo#4598] opened 2021-06-02 09:53 UTC
**Information**
DefectDojo tag v1.15
Api endpoint import-scan
When you try to import the result file from Checkmarx using the API or the Web UI and changing the active state to true and the verify state to True, the findings are always setted as inactive.

**Bug description**
Problem importing the Checkmarx file report using the "checkmarx scan" and "checkmarx scan detailed"  importer.
The problem is reproduced using the API endpoint (import-scan) and the WEB UI. Findigns state is always "Inactive" when the import process is done successfully setting the Active and Verified flag to True. It seems that these flags are ignored:

curl -X POST "https://defect-dojo.dmain/api/v2/import-scan/" -H  "accept: application/json" -H  "Content-Type: multipart/form-data" -H  "X-CSRFToken: token" -F "scan_date=2021-06-02" -F "minimum_severity=Info" -F "active=true" -F "verified=true" -F "scan_type=Checkmarx Scan" -F "file=@ssdlc-testing.xml;type=text/xml" -F "engagement=51" -F "close_old_findings=false" -F "push_to_jira=false"

![image](https://user-images.githubusercontent.com/85225790/120459875-e20ed400-c398-11eb-86ab-fa6fa8c44c4a.png)

**Expected behavior**
Finding state must change if you set the active or verify flag status to False or True.

**Comment by ssiriz** [comment] 2021-06-02 10:03
the file uploaded is attached
[ssdlc-testing.xml.zip](https://github.com/DefectDojo/django-DefectDojo/files/6583617/ssdlc-testing.xml.zip)

**Comment by ssiriz** [comment] 2021-07-05 14:13
Hello @devGregA , I will try to investigate how to solve the fix because is critical for me and my organisation solve it... Do you have some recommendation to locate the part of code that import Checkmarx results?

thank you,

**Comment by valentijnscholten** [comment] 2021-07-05 17:07
For some reason these values are hardcoded to be false, I don't know why: https://github.com/valentijnscholten/django-DefectDojo/blob/3957c7d7f4f32dfa2339494e406ac24675864a13/dojo/tools/checkmarx/parser.py#L122. Looks like very old code, I think it should be removed and let the fields go to default value, which will also allow the settings chosen in API request or UI to propagate.

**Comment by ssiriz** [comment] 2021-07-06 10:57
Thank for your answer @valentijnscholten , I have removed the parameters active and verified with the value False hardcoded and It solves the problem for the Checkmarx and Checkmarx Detailed Parser.

I am going to open a Pull Request with these changes. :)

**Comment by valentijnscholten** [comment] 2021-07-06 16:21
yes please :-)

**Comment by jcaillon** [comment] 2021-11-10 12:24
I can confirm that this issue has been fixed: Scan import for checkmarx is working fine with vers 2.4.1, issues are listed and active and unverified, as specified during the import.

![image](https://user-images.githubusercontent.com/11553075/141112558-9561fcb1-f663-492b-9c68-eb3f44b97e76.png)

**Comment by valentijnscholten** [comment] 2021-11-10 16:53
@jcaillon Thanks for letting us know, closing an issue always feels good.

**Closed** 2021-11-10 16:53 UTC
Labels: bug, good first issue
