### ISSUE TITLE
Deleting findings results in unexpected deletion

### ISSUE THREAD

**Issue by madchap** [DefectDojo/django-DefectDojo#3573] opened 2020-12-31 10:25 UTC
If you delete duplicate finding, then defectdojo will attempt to delete the original as well.
If you delete an original, duplicates get deleted as well.

We need to change this.

**Comment by valentijnscholten** [comment] 2021-03-26 21:41
talking about duplicates, this is a duplicate of #3057

**Closed by valentijnscholten** 2021-03-26 21:41 UTC
Labels: bug
