### ISSUE TITLE
Remove nmap scans integrated feature

### ISSUE THREAD

**Issue by damiencarol** [DefectDojo/django-DefectDojo#3974] opened 2021-03-02 18:06 UTC
https://defectdojo.readthedocs.io/en/latest/features.html#port-scans

**Comment by StefanFl** [comment] 2021-03-03 06:26
Have you decided who will do it? I am happy to volunteer.

**Comment by valentijnscholten** [comment] 2021-03-03 14:13
closing as duplicate of #3820

**Closed by valentijnscholten** 2021-03-03 14:13 UTC
Labels: bug

**Comment by damiencarol** [comment] 2021-03-04 07:07
@valentijnscholten this one was for documentation :D but ok!
