### ISSUE TITLE
Server 500 error when viewing finding if duplicate is True and duplicate_finding is None

### ISSUE THREAD

**Issue by keenan-v1** [DefectDojo/django-DefectDojo#2121] opened 2020-03-27 19:21 UTC
**Bug description**
When a finding has `duplicate` as `True` and yet `duplicate_finding` is `None` the server will give a 500 response when viewing that finding. This state can be achieved via the API or via Edit Finding and marking the finding as a duplicate.

**Steps to reproduce**
1. Edit a finding
2. Ensure Active and Verified are not checked, then check Duplicate
3. Save the finding.
 
**Expected behavior**
I expect the server to return the finding page even if `duplicate_finding` is `None` as you cannot assign a `duplicate_finding` due to it being not editable.

**Deployment method** *(select with an `X`)*
- [ ] Kubernetes
- [X] Docker
- [ ] setup.bash / legacy-setup.bash

**Environment information**
 - Operating System: Debian Stretch
 - DefectDojo Commit Message: 64d5f348: Merge pull request #2032 from DefectDojo/update-contributing-master [2020-03-12 22:41:42 +0100]

**Console logs** (optional)
https://pastebin.com/QCRgKp2F

**Additional context** (optional)
The cause of the 500 error is accessing `id` on a NoneType, which in this case is `duplicate_finding`. To fix the symptom, simply add `and self.duplicate_finding` to the if statement on line 1496. However I feel there's a greater issue that you can modify `duplicate` to `True` via the API and the Edit Finding page, yet you cannot indicate what original finding it is a duplicate of due to `duplicate_finding` being read-only.

**Comment by valentijnscholten** [comment] 2020-03-28 11:20
Lots has changed regarding this on `dev` branch. Could you confirm it's still present there?

**Comment by keenan-v1** [comment] 2020-03-30 15:38
> Lots has changed regarding this on `dev` branch. Could you confirm it's still present there?

Ah, I posted the commit message from the wrong branch. I was working out of dev. I'll do a pull and re-test though and confirm if it's still an issue.

**Comment by keenan-v1** [comment] 2020-03-30 15:53
Still able to be reproduced. Here's the commit I'm at:

d88b957d: Add component name and version for JFrog scans (#1979) [2020-03-23 16:28:01 +0100]

As I said, the cheap fix is just checking for `duplicate_finding` as that's where the exception is happening. The bigger fix is allowing us to link the actual duplicate from the Edit screen and via the API.

**Comment by valentijnscholten** [comment] 2020-03-30 15:56
That's not latest dev.

**Comment by keenan-v1** [comment] 2020-03-30 16:12
> That's not latest dev.

I edited the comment.

**Comment by Apipia** [comment] 2020-05-28 19:20
This is still an issue. 
The 500 Error comes from trying to load the page with duplicate_finding_set function in Models.py.
This will attempt to run this line:
`return Finding.objects.get(id=self.duplicate_finding.id).original_finding.all().order_by('title')`
if finding.duplicate, which is true in this case. 
however, self.dupcliate_finding is None.

There is some interesting behavior here that makes me wonder what the intended workflow should be. For certain findings, if DefectDojo is able to determine that it may be a duplicate, when you check "Duplicate" a drop-down menu occurs.
![image](https://user-images.githubusercontent.com/17787069/83183699-1ba16500-a0dd-11ea-981d-02db62f3bd30.png)
Allowing you to set the parent.

However, not all findings will have this behavior, yet checking "Duplicate" is still possible.
![image](https://user-images.githubusercontent.com/17787069/83183782-45f32280-a0dd-11ea-9a40-ef278696112a.png)
The error occurs in the latter case. 

An important question to ask here is this:
Can the user set the duplicate to any Finding they wish? I would think they should be able to, but that doesn't seem to be possible. If a bug-bounty report, for example, is a duplicate of another. They share very little data that would allow DefectDojo to consider them duplicates, but we know they are, and would like to mark them as such. 

Followup question:
How can, or is it even possible, to manually set the Finding that this Finding is a duplicate of? Does not seem possible via the API if one provides `duplicate_finding={FINDING_ID}`, this does nothing.

**Comment by Apipia** [comment] 2020-05-28 19:29
Possible solution would be the addition of an endpoint like `/finding/{duplicate_id}/duplicate/{original_id}` that accepts a POST body with the finding id of the duplicate Finding. The behavior at this endpoint will likely match the logic finding/views.py#mark_finding_duplicate.

**Comment by devGregA** [comment] 2020-06-30 21:20
Believe to be fixed by: https://github.com/DefectDojo/django-DefectDojo/pull/2506

**Closed** 2020-09-19 15:11 UTC
Labels: believe to be fixed, bug
